# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    vmware = {
      source  = "github.com/hashicorp/vmware"
      version = "~> 1"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "compression_level" {
  type    = string
  default = "6"
}

variable "cpus" {
  type    = string
  default = "1"
}

variable "disk_size" {
  type    = string
  default = "30000"
}

variable "headless" {
  type    = string
  default = "false"
}

variable "iso_checksum" {
  type    = string
  default = "9da6ae5b63a72161d0fd4480d0f090b250c4f6bf421474e4776e82eea5cb3143bf8936bf43244e438e74d581797fe87c7193bbefff19414e33932fe787b1400f"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha512"
}

variable "memory" {
  type    = string
  default = "2048"
}

variable "mirror" {
  type    = string
  default = "http://cdimage.debian.org/debian-cd"
}

variable "ssh_timeout" {
  type    = string
  default = "60m"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "vmware-iso" "autogenerated_1" {
  boot_command     = ["<esc><wait>", "auto ", "net.ifnames=0 ", "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ", "<enter>"]
  boot_wait        = "5s"
  disk_size        = "${var.disk_size}"
  guest_os_type    = "debian9-64"
  headless         = "${var.headless}"
  http_directory   = "http"
  iso_checksum     = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_url          = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.1.0-amd64-netinst.iso"
  output_directory = "output-debian-12-amd64-student"
  shutdown_command = "sudo systemctl poweroff"
  ssh_password     = "vagrant"
  ssh_timeout      = "${var.ssh_timeout}"
  ssh_username     = "vagrant"
  vm_name          = "packer-debian-12-amd64"
  vmx_data = {
    memsize  = "${var.memory}"
    numvcpus = "${var.cpus}"
  }
  vmx_remove_ethernet_interfaces = true
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.vmware-iso.autogenerated_1"]

  provisioner "shell" {
    scripts = ["scripts/virtualbox-iut-bookworm.sh", "scripts/vmware.sh", "scripts/minimize.sh", "scripts/cleanup.sh"]
  }

}
