---
- name: "vm3"
  node_name: "eva"
  resource_name: "vm3"
  vm_id: 1003
  agent:
    enabled: false
    trim: true
    type: "virtio"
  bios: "seabios"
  cpu:
    cores: 1
    sockets: 1
  cloud_init:
    type: "nocloud"
    datastore_id: "local-lvm"
    dns:
      domain: "homelab.lan"
      server: "1.1.1.1 1.0.0.1"
    ip_configs:
      - ipv4:
          address: "192.168.0.112/24"
          gateway: "192.168.0.254"
      # - ipv6:
      #     address: "fd91:0812:a17f:6194::10/64"
      #     gateway: "fd91:0812:a17f:6194::1"
    user_account:
      username: "ubuntu"
      password: "ubuntu"
      keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2j0Hf+W51tQBTwekIf1lQdEX1pNfY5TXw35P02nBHAqH69WzQpPJTuaYs+WmPbZ/066AssABYtE8JgR2gUzAWL010Yg1iNERPxy41UtFIF1HSV7wGi3kMruBzFCCbEBvbRFkJc1vQv4tS7G0UPtLiTHLYadsHq27A0lZJ/y/TsDvDTY0olbkfit3juMExy5uzCJN5Db1yiRNtBkl8vZP183kLatGtGygz1o9G6ywqZ51Tl2sgYH1ahCheuTv6Zn82B2jzrvisrza7hO0goEg2WR7SWbVl3AnA4YncJ5x9L8PXifXVCFVUj7p8PXqcu7KOixp9IGANvtiTfdvzm4Xg3BLRBKNJXWXW1f19MtPzOUMuRWru4hj6kX20/3C8WB8yco+qQlI0I6+5QYiGQtl4ZHsXcrCTyKtPmYwCdHv9XcEdDGXVNY/4oLm3rh06Nf8ZNx3phZj3xfZ8Lx+BohRRanVJifyKjucopcSy75b9lEMeWKlySLlTQjXDbBtPzSfupVE2Gvw3969J7uAIvvzASdEKdNgTF/ZEUnLexVI82HXpo2GHjr9Fj2B0JhSBfttsyd5LvubbuJ1HVOtPrax971vsUENoUuRLbJPbLoFdCoE5CKKReyjAYIbE9oDEIVt0KlnHI+gAsYg078uwyxrD8nallrBIx+eOG5hDmnum8w== jbriault@deezer.com
  clone:
    node_name: "eva"
    vm_id: 9000
    full: true
  disks:
    - disk1:
        interface: "scsi0"
        datastore_id: "local-lvm"
        size: 32
        file_format: "raw"
        cache: "none"
    - disk2:
        interface: "scsi1"
        datastore_id: "local-lvm"
        size: 32
        file_format: "raw"
        cache: "none"
  memory:
    dedicated: 512
  network_devices:
    - net1:
        bridge: "vmbr0"
        model: "virtio"
    - net2:
        bridge: "vmbr0"
        model: "virtio"
  on_boot: true
